name: "Compile"
description: "Executes a compilation."

inputs:
  path:
    required: true
    description: "Path to compile and test"
    default: src/

runs:
  using: "composite"
  steps:
      - name: Generate CMake project
        run: |
          SRC_FOLDER=$(pwd)/${{ inputs.path }}
          mkdir -p build && cd build
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            cmake ${SRC_FOLDER} -DBUILD_TESTS=1 -G "Visual Studio 17 2022" -A x64
          else
            cmake ${SRC_FOLDER} -DBUILD_TESTS=1 -G "Unix Makefiles"
          fi
          echo "CMake project generated in $(pwd)"
        shell: bash

      - name: Compile
        run: |
          cd build
          if [ ! -f CMakeCache.txt ]; then
            echo "CMake cache not found in $(pwd). Aborting."
            exit 1
          fi
          cmake --build . --config RelWithDebInfo -j $(nproc)
        shell: bash

      - name: Run Tests
        continue-on-error: false
        run: |
          set +e
          cd build
          ctest -C RelWithDebInfo --output-on-failure
        shell: bash
