name: 'Set Docker architecture, tag and image name'
description: 'Set Docker architecture, tag and image name'
inputs:
  system:
    description: 'Linux image system'
    required: true
  architecture:
    description: 'Linux image architecture'
    required: true
  docker_image_tag:
    description: 'Requested Docker image tag'
    required: true
  source_reference:
    description: 'Branch from wazuh/wazuh-agent repository to use.'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set ARCH
      shell: bash
      run: |
        if [ ${{ inputs.architecture }} = 'x86_64' ]; then
          arch="amd64"
        elif [ ${{ inputs.architecture }} = 'aarch64' ]; then
          arch="arm64"
        else
          arch=${{ inputs.architecture }}
        fi
        echo "ARCH=$arch" >> $GITHUB_ENV;

    - name: Set TAG and DOCKER_IMAGE_NAME
      shell: bash
      run: |
        VERSION="$(sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' VERSION.json)"
        if [ "${{ inputs.docker_image_tag }}" == "auto" ]; then
          echo "TAG=$VERSION" >> $GITHUB_ENV;
        elif [ "${{ inputs.docker_image_tag }}" == "developer" ]; then
          echo "TAG=$(sed 's|[/\]|--|g' <<< ${{ inputs.source_reference }})" >> $GITHUB_ENV;
        else
          echo "TAG=${{ inputs.docker_image_tag }}" >> $GITHUB_ENV;
        fi
        echo "DOCKER_IMAGE_NAME=pkg_${{ inputs.system }}_agent_builder_${{ env.ARCH }}" >> $GITHUB_ENV
