name: "Compile"
description: "Executes a compilation."

inputs:
  path:
    required: true
    description: "Path to compile and test"
    default: src/

runs:
  using: "composite"
  steps:
      - name: Generate CMake project
        run: |
          SRC_FOLDER=$(pwd)/${{ inputs.path }}
          mkdir -p build && cd build
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            cmake ${SRC_FOLDER} -DBUILD_TESTS=1 -G "Visual Studio 17 2022" -A x64
          else
            cmake ${SRC_FOLDER} -DBUILD_TESTS=1 -G "Unix Makefiles"
          fi
          echo "CMake project generated in $(pwd)"
        shell: bash

      - name: Compile
        run: |
          cd build
          if [ ! -f CMakeCache.txt ]; then
            echo "CMake cache not found in $(pwd). Aborting."
            exit 1
          fi
          cmake --build . --config RelWithDebInfo -j $(nproc)
        shell: bash
      
      - name: Zip artifact for testing
        if: ${{ inputs.upload_to_s3 }}
        run: zip build.zip $(pwd)/* -

      - name: Set up AWS CLI
        if: ${{ inputs.upload_to_s3 }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CI_INTERNAL_DEVELOPMENT_BUCKET_USER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.CI_INTERNAL_DEVELOPMENT_BUCKET_USER_SECRET_KEY }}
          aws-region: ${{ secrets.CI_AWS_REGION }}

      - name: Upload files to S3
        if: ${{ inputs.upload_to_s3 }}
        uses: ./.github/actions/4_s3_upload
        with:
          s3_uri: "s3://packages-dev.internal.wazuh.com/development/wazuh/5.x/main/packages"
          uploaded_file_name: build.zip
          uploaded_file_location: "/tmp"

