#!/bin/sh

# Copyright (C) 2015, Wazuh Inc.
# OSSEC         Controls Wazuh
# Author:       Daniel B. Cid <dcid@ossec.net>
# Modified for Debian by Michael Starks (patch by Costas Drogos)

### BEGIN INIT INFO
# Provides:          ossec
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:      $network
# Should-Stop:       $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop Wazuh
# Description:       Controls Wazuh daemons
#
### END INIT INFO

WAZUH_HOME=WAZUH_HOME_TMP
WAZUH_AGENT="$WAZUH_HOME/bin/wazuh-agent"

start() {
    # Define command to start the service
    cd /etc/opt/wazuh-agent && ${WAZUH_AGENT} &
}

stop() {
    # Define command to stop the service
    pkill -f ${WAZUH_AGENT}
}

status() {
    # ${WAZUH_AGENT} status
}

case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
restart)
    stop
    start
    ;;
status)
    status
    ;;
*)
    echo "*** Usage: $0 {start|stop|restart|status}"
    exit 1
esac
