name: Clang Format Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  clang-format:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Clang Format Check
      uses: ./.github/actions/clang_format
      with:
        path: 'src/'
        id: 'wazuh-agent'
