name: Run Tests

on:
  pull_request:
      types:
        - opened
        - synchronize
        - reopened
        
  workflow_run:
      workflows: [Compile]
      types: [completed]

jobs:
  ctest:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Run Tests
        continue-on-error: false
        run: |
          set +e
          cd build-${{ matrix.os }}/
          ctest -C RelWithDebInfo --output-on-failure
        shell: bash
