name: Run Tests

on:
  workflow_run:
      workflows: [Compile]
      types: [completed]

jobs:
  ctest:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ]
        #os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
        
      - name: Use build artifact
        run: |
          ls -la build/
          # Add steps to use the build artifact here
        shell: bash

      - name: Run Tests
        continue-on-error: false
        run: |
          set +e
          cd build/
          ctest -C RelWithDebInfo --output-on-failure
        shell: bash
